version: '3.8'

services:
  llm-mock-1c1g:
    image: llm-mock-server:latest
    container_name: llm-mock-1c1g
    ports:
      - "8081:8080"
    environment:
      - MAX_CONCURRENT=10000
      - WORKER_THREADS=2
      - RESPONSE_DELAY_SECONDS=10
      - PORT=8080
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
      net.ipv4.ip_local_port_range: "10001 65535"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  llm-mock-2c2g:
    image: llm-mock-server:latest
    container_name: llm-mock-2c2g
    ports:
      - "8082:8080"
    environment:
      - MAX_CONCURRENT=30000
      - WORKER_THREADS=4
      - RESPONSE_DELAY_SECONDS=10
      - PORT=8080
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
      net.ipv4.ip_local_port_range: "10001 65535"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

networks:
  default:
    name: llm-mock-network